language: ruby
rvm:
  - 2.3.0
bundler_args: --without production
before_install:
  - sudo apt-get install qt5-default libqt5webkit5-dev gstreamer1.0-plugins-base gstreamer1.0-tools gstreamer1.0-x
script:
  - bundle exec rails db:create db:migrate
  - bundle exec rspec
