language: ruby
rvm:
  - 2.3.0
bundler_args: --without production
gemfile:
  - rails/Gemfile
before_install:
  - gem update --system
  - gem --version
before_script:
  - bundle exec rake -f rails/Rakefile db:create
script:
  - bundle exec rake -f rails/Rakefile db:migrate
  - bundle exec rspec
