language: ruby
rvm:
  - 2.3.0
bundler_args: --without production
script:
  - bin/rails db:environment:set RAILS_ENV=test
  - bundle exec rake db:schema:load RAILS_ENV=test
  - bundle exec rspec
cache: bundler
